version: '3.8'

services:
       web:
         build: .
         container_name: web_app
         ports:
            - "5000:5000"

       nginx:
          image: nginx:latest
          container_name: nginx_proxy
          volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
          ports:
            - "80:80"
          depends_on: 
            - web     
